### ISSUE TITLE
Slack API issues?

### ISSUE THREAD

**Issue by MisterC925** [JackCuthbert/slack-fm#104]
Slack seems to have killed off the legacy API? 

    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),
[Slack] Getting user presence,
Error: internal_error,
    at Object.getSlackPresence (/app/dist/utils/slack.js:74:19),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
    at async main (/app/dist/index.js:42:29),

**Comment by JackCuthbert** [comment]
Oh no! Are you still having this issue? it's still working for me.

![image](https://user-images.githubusercontent.com/5564612/97135263-ea1fe900-17a3-11eb-90b6-8d4da35c09f5.png)

I think the legacy tokens will continue to work but you won't be able to generate any new ones:

![image](https://user-images.githubusercontent.com/5564612/97134985-20a93400-17a3-11eb-81aa-a56664e23588.png)

**Comment by MisterC925** [comment]
It started working again after a day or so but I as you noticed they've stopped issuing tokens so the end may be soon.


Thanks!
